version: '3.1'
  
services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: "${DB_CONTAINER_NAME}"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}"
    volumes:
      - ../db/data:/var/lib/postgresql/data
  db-ui:
    image: "${DB_UI_VERSION}"
    container_name: "${DB_UI_CONTAINER_NAME}"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${DB_UI_USER}"
      - "PGADMIN_DEFAULT_PASSWORD=${DB_UI_PASSWORD}"
    ports:
      - "${DB_UI_PORT}"